baseURL = "http://gnalb.at/"
languageCode = "en-us"
title = "gnalb.at"
theme = "gnalb.at"

[params]
    [params.footer]
        link = "https://github.com/gnalbat"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true