baseURL = "http://tabla.ng/"
languageCode = "en-us"
title = "tabla.ng"
theme = "tabla.ng"

[author]
    name = "Karlo Tablang"

[params]
    [params.footer]
        link = "https://github.com/gnalbat"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true